apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openeo-ingress
  namespace: spark-jobs
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  tls:
  - hosts: 
      - "{{ openeo_dns_name }}"
    secretName: openeocert
  rules:
    - host: "{{ openeo_dns_name }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  myspark-sparkapplication
                port:
                  number: 50001

